VERILOG_SOURCES += $(ROOT_DIR)/rtl/ram_1r1w_sync.sv
VERILOG_SOURCES += $(ROOT_DIR)/rtl/ram_1rw_sync.sv
VERILOG_SOURCES += $(ROOT_DIR)/rtl/skid_buffer.sv

VERILOG_SOURCES += $(ROOT_DIR)/rtl/soc/axil_pkg.sv
VERILOG_SOURCES += $(ROOT_DIR)/rtl/soc/ram_sync_axil.sv

TESTNAME := ram_sync_axil

include ../formal.mk
